#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-05-02"

[env.prod]
name = "referee-fyi-share"
compatibility_date = "2024-05-02"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "2ce07a6334454e018aa07a1adacbaae9" },
    { binding = "INVITATIONS", id = "f5c4fb7590e94433871d617492362aad" },
    { binding = "USERS", id = "b3a8d6eff5d54a79b2b0dd8156d07a8b" },
    { binding = "REQUEST_CODES", id = "fc4f29cb06d44fe5b7356a224605ffb8" },
    { binding = "SYSTEM_KEYS", id = "946437fe93124c53a120911049cb68da" },
    { binding = "ASSETS", id = "a38afb0b7a7641e4a007a499366c56bb" },
]
workers_dev = true

[env.prod.vars]
# TODO: replace with your own Cloudflare account email and Images account id
CLOUDFLARE_EMAIL = "brendan@bren.app"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "f9b9e088206092e25d77f0def608c799"

[env.staging]
name = "referee-fyi-share-staging"
compatibility_date = "2024-05-02"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "2ce07a6334454e018aa07a1adacbaae9", preview_id = "2ce07a6334454e018aa07a1adacbaae9" },
    { binding = "INVITATIONS", id = "f5c4fb7590e94433871d617492362aad", preview_id = "f5c4fb7590e94433871d617492362aad" },
    { binding = "USERS", id = "b3a8d6eff5d54a79b2b0dd8156d07a8b", preview_id = "b3a8d6eff5d54a79b2b0dd8156d07a8b" },
    { binding = "REQUEST_CODES", id = "fc4f29cb06d44fe5b7356a224605ffb8", preview_id = "fc4f29cb06d44fe5b7356a224605ffb8" },
    { binding = "SYSTEM_KEYS", id = "946437fe93124c53a120911049cb68da", preview_id = "946437fe93124c53a120911049cb68da" },
    { binding = "ASSETS", id = "a38afb0b7a7641e4a007a499366c56bb" },
]
workers_dev = true


[env.staging.vars]
# TODO: replace with your own Cloudflare account email and Images account id
CLOUDFLARE_EMAIL = "brendan@bren.app"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "f9b9e088206092e25d77f0def608c799"

[[env.staging.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[env.prod.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShareInstance"]
