#:schema node_modules/wrangler/config-schema.json
name = "roboref-share"
compatibility_date = "2026-06-20"

[env.live]
name = "roboref-share"
compatibility_date = "2026-06-20"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "2ce07a6334454e018aa07a1adacbaae9" },
    { binding = "INVITATIONS", id = "f5c4fb7590e94433871d617492362aad" },
    { binding = "USERS", id = "b3a8d6eff5d54a79b2b0dd8156d07a8b" },
    { binding = "REQUEST_CODES", id = "fc4f29cb06d44fe5b7356a224605ffb8" },
    { binding = "SYSTEM_KEYS", id = "946437fe93124c53a120911049cb68da" },
    { binding = "ASSETS", id = "a38afb0b7a7641e4a007a499366c56bb" },
]
routes = [{ pattern = "share.roboref.fyi", custom_domain = true }]
workers_dev = true

[env.test]
name = "roboref-share-test"
compatibility_date = "2026-06-20"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "e73e437bf1fb4428988df66b0da81b69" },
    { binding = "INVITATIONS", id = "75d11514b23845fd944de3f6c9cf3c7c" },
    { binding = "USERS", id = "57285cbfafe649d1956f7aae5ee8894c" },
    { binding = "REQUEST_CODES", id = "5dd9ec8bd9544d9b86a4b495b9ec7a78" },
    { binding = "SYSTEM_KEYS", id = "3cbdcb8eed3d4047a75b10077dfd603c" },
    { binding = "ASSETS", id = "2573480f7f0f416f97c3014df3f401fd" },
]
routes = [{ pattern = "test.share.roboref.fyi", custom_domain = true }]
workers_dev = true

[[env.live.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "roboref-images"

# [[env.test.r2_buckets]]
# binding = "IMAGES_BUCKET"
# bucket_name = "roboref-images"

[[env.test.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[env.live.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShareInstance"]

