/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkuRouteRouteImport } from './routes/$sku/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ShareRouteImport } from './routes/share'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SkuIndexRouteImport } from './routes/$sku/index'
import { Route as SkuDeletedRouteImport } from './routes/$sku/deleted'
import { Route as SkuDevtoolsRouteImport } from './routes/$sku/devtools'
import { Route as SkuFiltersRouteImport } from './routes/$sku/filters'
import { Route as SkuInviteRouteImport } from './routes/$sku/invite'
import { Route as SkuJoinRouteImport } from './routes/$sku/join'
import { Route as SkuNewRouteImport } from './routes/$sku/new'
import { Route as SkuSkillsRouteImport } from './routes/$sku/skills'
import { Route as SkuSummaryRouteImport } from './routes/$sku/summary'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SkuDivisionIndexRouteImport } from './routes/$sku/$division/index'
import { Route as SkuEntryIncidentIdRouteImport } from './routes/$sku/entry/$incidentId'
import { Route as SkuMatchMatchIdRouteImport } from './routes/$sku/match/$matchId'
import { Route as SkuTeamTeamRouteRouteImport } from './routes/$sku/team/$team/route'
import { Route as SkuTeamTeamIndexRouteImport } from './routes/$sku/team/$team/index'
import { Route as SkuTeamTeamTeamNotesRouteImport } from './routes/$sku/team/$team/teamNotes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuRouteRoute = SkuRouteRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuIndexRoute = SkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuDeletedRoute = SkuDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuDevtoolsRoute = SkuDevtoolsRouteImport.update({
  id: '/devtools',
  path: '/devtools',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuFiltersRoute = SkuFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuInviteRoute = SkuInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuJoinRoute = SkuJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuNewRoute = SkuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuSkillsRoute = SkuSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuSummaryRoute = SkuSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SkuDivisionIndexRoute = SkuDivisionIndexRouteImport.update({
  id: '/$division/',
  path: '/$division/',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuEntryIncidentIdRoute = SkuEntryIncidentIdRouteImport.update({
  id: '/entry/$incidentId',
  path: '/entry/$incidentId',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuMatchMatchIdRoute = SkuMatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuTeamTeamRouteRoute = SkuTeamTeamRouteRouteImport.update({
  id: '/team/$team',
  path: '/team/$team',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuTeamTeamIndexRoute = SkuTeamTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkuTeamTeamRouteRoute,
} as any)
const SkuTeamTeamTeamNotesRoute = SkuTeamTeamTeamNotesRouteImport.update({
  id: '/teamNotes',
  path: '/teamNotes',
  getParentRoute: () => SkuTeamTeamRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/filters': typeof SkuFiltersRoute
  '/$sku/invite': typeof SkuInviteRoute
  '/$sku/join': typeof SkuJoinRoute
  '/$sku/new': typeof SkuNewRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRouteRouteWithChildren
  '/$sku/entry/$incidentId': typeof SkuEntryIncidentIdRoute
  '/$sku/match/$matchId': typeof SkuMatchMatchIdRoute
  '/$sku/$division/': typeof SkuDivisionIndexRoute
  '/$sku/team/$team/teamNotes': typeof SkuTeamTeamTeamNotesRoute
  '/$sku/team/$team/': typeof SkuTeamTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/filters': typeof SkuFiltersRoute
  '/$sku/invite': typeof SkuInviteRoute
  '/$sku/join': typeof SkuJoinRoute
  '/$sku/new': typeof SkuNewRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku': typeof SkuIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/$sku/entry/$incidentId': typeof SkuEntryIncidentIdRoute
  '/$sku/match/$matchId': typeof SkuMatchMatchIdRoute
  '/$sku/$division': typeof SkuDivisionIndexRoute
  '/$sku/team/$team/teamNotes': typeof SkuTeamTeamTeamNotesRoute
  '/$sku/team/$team': typeof SkuTeamTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/share': typeof ShareRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/filters': typeof SkuFiltersRoute
  '/$sku/invite': typeof SkuInviteRoute
  '/$sku/join': typeof SkuJoinRoute
  '/$sku/new': typeof SkuNewRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRouteRouteWithChildren
  '/$sku/entry/$incidentId': typeof SkuEntryIncidentIdRoute
  '/$sku/match/$matchId': typeof SkuMatchMatchIdRoute
  '/$sku/$division/': typeof SkuDivisionIndexRoute
  '/$sku/team/$team/teamNotes': typeof SkuTeamTeamTeamNotesRoute
  '/$sku/team/$team/': typeof SkuTeamTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sku'
    | '/settings'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/share'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/filters'
    | '/$sku/invite'
    | '/$sku/join'
    | '/$sku/new'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/settings/'
    | '/$sku/team/$team'
    | '/$sku/entry/$incidentId'
    | '/$sku/match/$matchId'
    | '/$sku/$division/'
    | '/$sku/team/$team/teamNotes'
    | '/$sku/team/$team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/share'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/filters'
    | '/$sku/invite'
    | '/$sku/join'
    | '/$sku/new'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku'
    | '/settings'
    | '/$sku/entry/$incidentId'
    | '/$sku/match/$matchId'
    | '/$sku/$division'
    | '/$sku/team/$team/teamNotes'
    | '/$sku/team/$team'
  id:
    | '__root__'
    | '/'
    | '/$sku'
    | '/settings'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/share'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/filters'
    | '/$sku/invite'
    | '/$sku/join'
    | '/$sku/new'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/settings/'
    | '/$sku/team/$team'
    | '/$sku/entry/$incidentId'
    | '/$sku/match/$matchId'
    | '/$sku/$division/'
    | '/$sku/team/$team/teamNotes'
    | '/$sku/team/$team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkuRouteRoute: typeof SkuRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  ShareRoute: typeof ShareRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sku': {
      id: '/$sku'
      path: '/$sku'
      fullPath: '/$sku'
      preLoaderRoute: typeof SkuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sku/': {
      id: '/$sku/'
      path: '/'
      fullPath: '/$sku/'
      preLoaderRoute: typeof SkuIndexRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/deleted': {
      id: '/$sku/deleted'
      path: '/deleted'
      fullPath: '/$sku/deleted'
      preLoaderRoute: typeof SkuDeletedRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/devtools': {
      id: '/$sku/devtools'
      path: '/devtools'
      fullPath: '/$sku/devtools'
      preLoaderRoute: typeof SkuDevtoolsRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/filters': {
      id: '/$sku/filters'
      path: '/filters'
      fullPath: '/$sku/filters'
      preLoaderRoute: typeof SkuFiltersRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/invite': {
      id: '/$sku/invite'
      path: '/invite'
      fullPath: '/$sku/invite'
      preLoaderRoute: typeof SkuInviteRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/join': {
      id: '/$sku/join'
      path: '/join'
      fullPath: '/$sku/join'
      preLoaderRoute: typeof SkuJoinRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/new': {
      id: '/$sku/new'
      path: '/new'
      fullPath: '/$sku/new'
      preLoaderRoute: typeof SkuNewRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/skills': {
      id: '/$sku/skills'
      path: '/skills'
      fullPath: '/$sku/skills'
      preLoaderRoute: typeof SkuSkillsRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/summary': {
      id: '/$sku/summary'
      path: '/summary'
      fullPath: '/$sku/summary'
      preLoaderRoute: typeof SkuSummaryRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/$sku/$division/': {
      id: '/$sku/$division/'
      path: '/$division'
      fullPath: '/$sku/$division/'
      preLoaderRoute: typeof SkuDivisionIndexRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/entry/$incidentId': {
      id: '/$sku/entry/$incidentId'
      path: '/entry/$incidentId'
      fullPath: '/$sku/entry/$incidentId'
      preLoaderRoute: typeof SkuEntryIncidentIdRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/match/$matchId': {
      id: '/$sku/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/$sku/match/$matchId'
      preLoaderRoute: typeof SkuMatchMatchIdRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/team/$team': {
      id: '/$sku/team/$team'
      path: '/team/$team'
      fullPath: '/$sku/team/$team'
      preLoaderRoute: typeof SkuTeamTeamRouteRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/team/$team/': {
      id: '/$sku/team/$team/'
      path: '/'
      fullPath: '/$sku/team/$team/'
      preLoaderRoute: typeof SkuTeamTeamIndexRouteImport
      parentRoute: typeof SkuTeamTeamRouteRoute
    }
    '/$sku/team/$team/teamNotes': {
      id: '/$sku/team/$team/teamNotes'
      path: '/teamNotes'
      fullPath: '/$sku/team/$team/teamNotes'
      preLoaderRoute: typeof SkuTeamTeamTeamNotesRouteImport
      parentRoute: typeof SkuTeamTeamRouteRoute
    }
  }
}

interface SkuTeamTeamRouteRouteChildren {
  SkuTeamTeamTeamNotesRoute: typeof SkuTeamTeamTeamNotesRoute
  SkuTeamTeamIndexRoute: typeof SkuTeamTeamIndexRoute
}

const SkuTeamTeamRouteRouteChildren: SkuTeamTeamRouteRouteChildren = {
  SkuTeamTeamTeamNotesRoute: SkuTeamTeamTeamNotesRoute,
  SkuTeamTeamIndexRoute: SkuTeamTeamIndexRoute,
}

const SkuTeamTeamRouteRouteWithChildren =
  SkuTeamTeamRouteRoute._addFileChildren(SkuTeamTeamRouteRouteChildren)

interface SkuRouteRouteChildren {
  SkuDeletedRoute: typeof SkuDeletedRoute
  SkuDevtoolsRoute: typeof SkuDevtoolsRoute
  SkuFiltersRoute: typeof SkuFiltersRoute
  SkuInviteRoute: typeof SkuInviteRoute
  SkuJoinRoute: typeof SkuJoinRoute
  SkuNewRoute: typeof SkuNewRoute
  SkuSkillsRoute: typeof SkuSkillsRoute
  SkuSummaryRoute: typeof SkuSummaryRoute
  SkuIndexRoute: typeof SkuIndexRoute
  SkuTeamTeamRouteRoute: typeof SkuTeamTeamRouteRouteWithChildren
  SkuEntryIncidentIdRoute: typeof SkuEntryIncidentIdRoute
  SkuMatchMatchIdRoute: typeof SkuMatchMatchIdRoute
  SkuDivisionIndexRoute: typeof SkuDivisionIndexRoute
}

const SkuRouteRouteChildren: SkuRouteRouteChildren = {
  SkuDeletedRoute: SkuDeletedRoute,
  SkuDevtoolsRoute: SkuDevtoolsRoute,
  SkuFiltersRoute: SkuFiltersRoute,
  SkuInviteRoute: SkuInviteRoute,
  SkuJoinRoute: SkuJoinRoute,
  SkuNewRoute: SkuNewRoute,
  SkuSkillsRoute: SkuSkillsRoute,
  SkuSummaryRoute: SkuSummaryRoute,
  SkuIndexRoute: SkuIndexRoute,
  SkuTeamTeamRouteRoute: SkuTeamTeamRouteRouteWithChildren,
  SkuEntryIncidentIdRoute: SkuEntryIncidentIdRoute,
  SkuMatchMatchIdRoute: SkuMatchMatchIdRoute,
  SkuDivisionIndexRoute: SkuDivisionIndexRoute,
}

const SkuRouteRouteWithChildren = SkuRouteRoute._addFileChildren(
  SkuRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkuRouteRoute: SkuRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  ShareRoute: ShareRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
