/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkuRouteRouteImport } from './routes/$sku/route'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SkuIndexRouteImport } from './routes/$sku/index'
import { Route as SkuDeletedRouteImport } from './routes/$sku/deleted'
import { Route as SkuDevtoolsRouteImport } from './routes/$sku/devtools'
import { Route as SkuSkillsRouteImport } from './routes/$sku/skills'
import { Route as SkuSummaryRouteImport } from './routes/$sku/summary'
import { Route as SkuDivisionIndexRouteImport } from './routes/$sku/$division/index'
import { Route as SkuTeamTeamRouteImport } from './routes/$sku/team/$team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuRouteRoute = SkuRouteRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuIndexRoute = SkuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuDeletedRoute = SkuDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuDevtoolsRoute = SkuDevtoolsRouteImport.update({
  id: '/devtools',
  path: '/devtools',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuSkillsRoute = SkuSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuSummaryRoute = SkuSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuDivisionIndexRoute = SkuDivisionIndexRouteImport.update({
  id: '/$division/',
  path: '/$division/',
  getParentRoute: () => SkuRouteRoute,
} as any)
const SkuTeamTeamRoute = SkuTeamTeamRouteImport.update({
  id: '/team/$team',
  path: '/team/$team',
  getParentRoute: () => SkuRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/$sku/$division/': typeof SkuDivisionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/$sku/$division': typeof SkuDivisionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/$sku/$division/': typeof SkuDivisionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sku'
    | '/events'
    | '/privacy'
    | '/settings'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/$sku/team/$team'
    | '/$sku/$division/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/privacy'
    | '/settings'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku'
    | '/$sku/team/$team'
    | '/$sku/$division'
  id:
    | '__root__'
    | '/'
    | '/$sku'
    | '/events'
    | '/privacy'
    | '/settings'
    | '/updates'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/$sku/team/$team'
    | '/$sku/$division/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkuRouteRoute: typeof SkuRouteRouteWithChildren
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sku': {
      id: '/$sku'
      path: '/$sku'
      fullPath: '/$sku'
      preLoaderRoute: typeof SkuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$sku/': {
      id: '/$sku/'
      path: '/'
      fullPath: '/$sku/'
      preLoaderRoute: typeof SkuIndexRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/deleted': {
      id: '/$sku/deleted'
      path: '/deleted'
      fullPath: '/$sku/deleted'
      preLoaderRoute: typeof SkuDeletedRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/devtools': {
      id: '/$sku/devtools'
      path: '/devtools'
      fullPath: '/$sku/devtools'
      preLoaderRoute: typeof SkuDevtoolsRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/skills': {
      id: '/$sku/skills'
      path: '/skills'
      fullPath: '/$sku/skills'
      preLoaderRoute: typeof SkuSkillsRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/summary': {
      id: '/$sku/summary'
      path: '/summary'
      fullPath: '/$sku/summary'
      preLoaderRoute: typeof SkuSummaryRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/$division/': {
      id: '/$sku/$division/'
      path: '/$division'
      fullPath: '/$sku/$division/'
      preLoaderRoute: typeof SkuDivisionIndexRouteImport
      parentRoute: typeof SkuRouteRoute
    }
    '/$sku/team/$team': {
      id: '/$sku/team/$team'
      path: '/team/$team'
      fullPath: '/$sku/team/$team'
      preLoaderRoute: typeof SkuTeamTeamRouteImport
      parentRoute: typeof SkuRouteRoute
    }
  }
}

interface SkuRouteRouteChildren {
  SkuDeletedRoute: typeof SkuDeletedRoute
  SkuDevtoolsRoute: typeof SkuDevtoolsRoute
  SkuSkillsRoute: typeof SkuSkillsRoute
  SkuSummaryRoute: typeof SkuSummaryRoute
  SkuIndexRoute: typeof SkuIndexRoute
  SkuTeamTeamRoute: typeof SkuTeamTeamRoute
  SkuDivisionIndexRoute: typeof SkuDivisionIndexRoute
}

const SkuRouteRouteChildren: SkuRouteRouteChildren = {
  SkuDeletedRoute: SkuDeletedRoute,
  SkuDevtoolsRoute: SkuDevtoolsRoute,
  SkuSkillsRoute: SkuSkillsRoute,
  SkuSummaryRoute: SkuSummaryRoute,
  SkuIndexRoute: SkuIndexRoute,
  SkuTeamTeamRoute: SkuTeamTeamRoute,
  SkuDivisionIndexRoute: SkuDivisionIndexRoute,
}

const SkuRouteRouteWithChildren = SkuRouteRoute._addFileChildren(
  SkuRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkuRouteRoute: SkuRouteRouteWithChildren,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
